[package]
name = "ipp"
version = "0.3.0"
authors = ["Dmitry Pankratov <dmitry@pankratov.net>"]
description = "IPP print protocol implementation for Rust"
license = "MIT"
repository = "https://github.com/dremon/ipp.rs"
documentation = "https://docs.rs/ipp"
readme = "README.md"
keywords = ["ipp", "print", "cups", "printing", "protocol"]
edition = "2018"

[lib]
name = "ipp"

[dependencies]
ipp-proto = { version = "0.3.0", path = "../ipp-proto" }
ipp-client = { version = "0.3.0", path = "../ipp-client", optional = true }
ipp-server = { version = "0.3.0", path = "../ipp-server", optional = true }
ipp-util = { version = "0.3.0", path = "../ipp-util", optional = true }

[dev-dependencies]
tokio = "0.1"
futures = "0.1"
env_logger = "0.6"
num-traits = "0.2"

[features]
default = ["client"]
client = ["ipp-client"]
server = ["ipp-server"]
util = ["ipp-util"]
