[package]
name = "ipp"
version = "4.0.0"
authors = ["Dmitry Pankratov <dmitry@pankratov.net>"]
description = "Asynchronous IPP print protocol implementation"
license = "MIT/Apache-2.0"
repository = "https://github.com/ancwrd1/ipp.rs"
documentation = "https://docs.rs/ipp"
readme = "README.md"
keywords = ["ipp", "print", "cups", "printing", "protocol"]
edition = "2018"

[lib]
name = "ipp"

[dependencies]
enum-as-inner = "0.5"
enum-primitive-derive = "0.2"
futures-executor = { version = "0.3", optional = true }
log = "0.4"
num-traits = "0.2"
bytes = "1"
thiserror = "1"
http = "0.2"
serde = { version = "1", optional = true, features = ["derive"] }
ureq = { version = "2", default-features = false, optional = true }
native-tls = { version = "0.2", optional = true }

[dependencies.futures-util]
version = "0.3"
optional = true
default-features = false
features = ["io"]

[dependencies.reqwest]
version = "0.11"
optional = true
default-features = false
features = ["stream"]

[dependencies.tokio-util]
version = "0.7"
optional = true
features = ["io", "compat"]

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }

[features]
default = ["async-client", "client", "tls"]
async-client = ["async", "reqwest", "tokio-util"]
client = ["ureq"]
async = ["futures-util", "futures-executor"]
serde = ["dep:serde", "bytes/serde"]
tls = []
__async_tls = ["reqwest/native-tls"]
__sync_tls = ["ureq/native-tls"]
