[package]
name = "ipp"
version = "3.0.0"
authors = ["Dmitry Pankratov <dmitry@pankratov.net>"]
description = "Asynchronous IPP print protocol implementation"
license = "MIT"
repository = "https://github.com/ancwrd1/ipp.rs"
documentation = "https://docs.rs/ipp"
readme = "README.md"
keywords = ["ipp", "print", "cups", "printing", "protocol"]
edition = "2018"

[lib]
name = "ipp"

[dependencies]
enum-as-inner = "0.3"
enum-primitive-derive = "0.2"
futures-util = {version = "0.3", default-features = false, features = ["io"] }
log = "0.4"
num-traits = "0.2"
bytes = "1"
thiserror = "1"
http = "0.2"

[dev-dependencies]
env_logger = "0.8"
futures = "0.3"

[features]
default = ["default-client"]
default-client = ["client-reqwest"]
client-isahc = ["isahc"]
client-reqwest = ["reqwest", "tokio-util"]

[dependencies.isahc]
version = "1"
optional = true
default-features = false
features = ["static-curl"]

[dependencies.reqwest]
version = "0.11"
optional = true
default-features = false
features = ["native-tls", "stream"]

[dependencies.tokio-util]
version = "0.6"
optional = true
features = ["io", "compat"]
