[package]
name = "ipp"
version = "0.4.0"
authors = ["Dmitry Pankratov <dmitry@pankratov.net>"]
description = "IPP print protocol implementation for Rust"
license = "MIT"
repository = "https://github.com/dremon/ipp.rs"
documentation = "https://docs.rs/ipp"
readme = "README.md"
keywords = ["ipp", "print", "cups", "printing", "protocol"]
edition = "2018"

[lib]
name = "ipp"

[dependencies]
ipp-proto = { version = "0.4.0", path = "../ipp-proto" }
ipp-client = { version = "0.4.0", path = "../ipp-client", optional = true }
ipp-util = { version = "0.4.0", path = "../ipp-util", optional = true }

[dev-dependencies]
env_logger = "0.7"
async-std = "1"

[features]
default = ["client"]
client = ["ipp-client"]
util = ["ipp-util"]
