[package]
name = "ipp"
version = "0.4.0"
authors = ["Dmitry Pankratov <dmitry@pankratov.net>"]
description = "IPP print protocol implementation for Rust"
license = "MIT"
repository = "https://github.com/dremon/ipp.rs"
documentation = "https://docs.rs/ipp"
readme = "README.md"
keywords = ["ipp", "print", "cups", "printing", "protocol"]
edition = "2018"

[lib]
name = "ipp"

[dependencies]
enum-as-inner = "0.3"
enum-primitive-derive = "0.1"
futures = "0.3"
log = "0.4"
num-traits = "0.2"
bytes = "0.5"

[dev-dependencies]
env_logger = "0.7"
futures = "0.3"

[features]
default = ["client"]
client = ["isahc"]

[dependencies.isahc]
version = "0.8"
optional = true
default-features = false
features = ["static-curl", "http2"]
