[package]
name = "ipp-util"
version = "0.3.0"
authors = ["Dmitry Pankratov <dmitry@pankratov.net>"]
description = "IPP utility and C shared library"
license = "MIT"
repository = "https://github.com/dremon/ipp.rs"
documentation = "https://docs.rs/ipp"
readme = "README.md"
keywords = ["ipp", "printing", "protocol"]

[lib]
crate_type = ["cdylib", "lib"]

[dependencies]
ipp-client = { path = "../ipp-client" }
ipp-parse = { path = "../ipp-parse" }
ipp-proto = { path = "../ipp-proto" }
pretty_env_logger = "0.2"
clap = "2.32"
num-traits = "0.2"
log = "0.4"
