[package]
name = "ipp-util"
version = "0.3.0"
authors = ["Dmitry Pankratov <dmitry@pankratov.net>"]
description = "IPP high-level utility"
license = "MIT"
repository = "https://github.com/dremon/ipp.rs"
documentation = "https://docs.rs/ipp"
readme = "README.md"
keywords = ["ipp", "print", "cups", "printing", "protocol"]
edition = "2018"

[dependencies]
ipp-client = { version = "0.3.0", path = "../ipp-client" }
ipp-proto = { version = "0.3.0", path = "../ipp-proto" }
pretty_env_logger = "0.3"
structopt = "0.3"
log = "0.4"
futures = "0.1"
tokio = "0.1"
