[package]
name = "ipp-util"
version = "1.0.1"
authors = ["Dmitry Pankratov <dmitry@pankratov.net>"]
description = "IPP command line print utility"
license = "MIT"
repository = "https://github.com/dremon/ipp.rs"
documentation = "https://docs.rs/ipp"
readme = "README.md"
keywords = ["ipp", "print", "cups", "printing", "protocol"]
edition = "2018"

[[bin]]
name = "ipputil"
path = "src/main.rs"

[dependencies]
ipp = { version = "1.0.1", path = "../ipp" }
env_logger = "0.7"
structopt = "0.3"
futures = "0.3"
