[package]
name = "ipp"
version = "0.1.0"
authors = ["Dmitry Pankratov <dmitry@pankratov.net>"]
description = "IPP print protocol implementation for Rust"
license = "MIT"
repository = "https://github.com/dremon/ipp.rs"
documentation = "https://dremon.github.io/ipp.rs/doc/ipp"
readme = "README.md"
keywords = ["ipp", "printing", "protocol"]

[dependencies]
byteorder = "1.1"
log = "0.3"
env_logger = "0.4"
enum_primitive = "0.1"
lazy_static = "0.2"
reqwest = "0.8"
url = "1.5"

[dev-dependencies]
hyper = "0.10"
