[package]
name = "ipp"
version = "0.2.1"
authors = ["Dmitry Pankratov <dmitry@pankratov.net>"]
description = "IPP print protocol implementation for Rust"
license = "MIT"
repository = "https://github.com/dremon/ipp.rs"
documentation = "https://docs.rs/ipp"
readme = "README.md"
keywords = ["ipp", "printing", "protocol"]

[workspace]
members = [ "ipp-parse", "ipp-proto", "ipp-client", "ipp-server", "ipp-dylib" ]

[dev-dependencies]
env_logger = "0.5"
hyper = "0.12"
lazy_static = "1.2"
futures = "0.1"
ippparse = { path = "ipp-parse" }
ippproto = { path = "ipp-proto" }
ippclient = { path = "ipp-client" }
ippserver = { path = "ipp-server" }
