[package]
name = "ipp"
version = "0.3.0"
authors = ["Dmitry Pankratov <dmitry@pankratov.net>"]
description = "IPP print protocol implementation for Rust"
license = "MIT"
repository = "https://github.com/dremon/ipp.rs"
documentation = "https://docs.rs/ipp"
readme = "README.md"
keywords = ["ipp", "printing", "protocol"]

[lib]
crate_type = ["cdylib"]
name = "ipputil"

[workspace]
members = [ ".", "ipp-parse", "ipp-proto", "ipp-client", "ipp-server" ]

[dev-dependencies]
ippparse = { path = "ipp-parse" }
ippproto = { path = "ipp-proto" }
ippserver = { path = "ipp-server" }
lazy_static = "1.2"
hyper = "0.12"
futures = "0.1"

[dependencies]
env_logger = "0.5"
ippclient = { path = "ipp-client" }
