[package]
name = "ipp-client"
version = "0.3.0"
authors = ["Dmitry Pankratov <dmitry@pankratov.net>"]
description = "IPP client based on reqwest"
license = "MIT"
repository = "https://github.com/dremon/ipp.rs"
documentation = "https://docs.rs/ipp"
readme = "README.md"
keywords = ["ipp", "printing", "protocol"]

[lib]
name = "ippclient"

[dependencies]
ipp-proto = { path = "../ipp-proto" }
ipp-parse = { path = "../ipp-parse" }
num-traits = "0.2"
reqwest = "0.9"
url = "1.7"
log = "0.4"

[dev-dependencies]
futures = "0.1"
env_logger = "0.5"
