[package]
name = "ippclient"
version = "0.3.0"
authors = ["Dmitry Pankratov <dmitry@pankratov.net>"]
description = "IPP client based on reqwest"
license = "MIT"
repository = "https://github.com/dremon/ipp.rs"
documentation = "https://docs.rs/ipp"
readme = "README.md"
keywords = ["ipp", "printing", "protocol"]

[dependencies]
ippproto = { path = "../ipp-proto" }
ippparse = { path = "../ipp-parse" }
reqwest = "0.9"
clap = "2.32"
num-traits = "0.2"
url = "1.7"
env_logger = "0.5"
log = "0.4"
