[package]
name = "ipp-client"
version = "0.3.0"
authors = ["Dmitry Pankratov <dmitry@pankratov.net>"]
description = "IPP client based on reqwest"
license = "MIT"
repository = "https://github.com/dremon/ipp.rs"
documentation = "https://docs.rs/ipp"
readme = "README.md"
keywords = ["ipp", "print", "cups", "printing", "protocol"]
edition = "2018"

[dependencies]
ipp-proto = { version = "0.3.0", path = "../ipp-proto" }
num-traits = "0.2"
reqwest = { git = "https://github.com/seanmonstar/reqwest.git" }
url = "1"
log = "0.4"
futures = "0.1"
percent-encoding = "1.0"

[dev-dependencies]
tokio = "0.1"
futures = "0.1"
env_logger = "0.6"
