[package]
name = "ipp-util"
version = "3.0.0"
authors = ["Dmitry Pankratov <dmitry@pankratov.net>"]
description = "IPP command line print utility"
license = "MIT/Apache-2.0"
repository = "https://github.com/ancwrd1/ipp.rs"
documentation = "https://docs.rs/ipp"
readme = "README.md"
keywords = ["ipp", "print", "cups", "printing", "protocol"]
edition = "2018"

[[bin]]
name = "ipputil"
path = "src/main.rs"

[dependencies]
ipp = { path = "../ipp", version = "3.0.0" }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
env_logger = "0.9"
clap = "3.0.0-beta.5"
