[package]
name = "ipp-server"
version = "0.3.0"
authors = ["Dmitry Pankratov <dmitry@pankratov.net>"]
description = "Helpers to make IPP servers"
license = "MIT"
repository = "https://github.com/dremon/ipp.rs"
documentation = "https://docs.rs/ipp"
readme = "README.md"
keywords = ["ipp", "printing", "protocol"]

[dependencies]
num-traits = "0.2"
ipp-parse = { version = "0.3.0", path = "../ipp-parse" }
ipp-proto = { version = "0.3.0", path = "../ipp-proto" }

[dev-dependencies]
ipp-server = { path = "../ipp-server" }
lazy_static = "1.2"
hyper = "0.12"
futures = "0.1"
