[package]
name = "ippproto"
version = "0.3.0"
authors = ["Dmitry Pankratov <dmitry@pankratov.net>"]
description = "High level IPP protocol definitions"
license = "MIT"
repository = "https://github.com/dremon/ipp.rs"
documentation = "https://docs.rs/ipp"
readme = "README.md"
keywords = ["ipp", "printing", "protocol"]

[dependencies]
ippparse = { path = "../ipp-parse" }
log = "0.4"
